const path = require("path");

module.exports = {
  content: [
    path.resolve(__dirname, "index.html"),
    path.resolve(__dirname, "src/**/*.js"),
  ],
  css: [
    path.resolve(__dirname, "src/styles/Analytics.css"),
    path.resolve(__dirname, "src/styles/animations.css"),
    path.resolve(__dirname, "src/styles/App.css"),
    path.resolve(__dirname, "src/styles/DashboardAnimations.css"),
    path.resolve(__dirname, "src/styles/index.css"),
    path.resolve(__dirname, "src/styles/Login.css"),
    path.resolve(__dirname, "src/styles/NotFound.css"),
  ],
  output: path.resolve(__dirname, "src/styles/cleaned.css"),
  safelist: [
    "animate-visible",
    "animate-on-scroll",
    "animate-fade-up",
    "animate-fade-in",
    "animate-glow",
    "animate-no-hide",
    "animate-zoom-in",
    "visible",
    "sequential-item",
    "has-sequential-children",
    "active",
    "active-nav",
    "dragging",
    "visible",
    "fade-out",
    "tabs-hidden",
    "sidebar-mob",
    "with-details",
    "dash-sel-page-loading",
    "new-request",
    "status-new",
    "status-read",
    "status-replied",
    "status-archived",
    "project-card",
    "tech-card",
    "feature-card",
    "contact-card",
    "contact-form",
    "project-description-box",
    "toast",
    "form-status",
    "success",
    "warning",
    "error",
    "dashboard-card",
    "order-instructions",
    "add-project-page",
    "input-field",
    "form-submit-button",
    "projects-container",
    "page-title",
    "dashboard-page-header",
    "tech-selection",
    "thumb",
    "sidebar-link",
    "sidebar",
    "dashboard-page",
    "main-content",
    "splash-screen",
    "portfolio-tabs",
    "portfolio-tab",
    "project-card",
    "tech-card",
    "feature-card",
    "contact-card",
    "contact-form",
    "portfolio-footer",
  ],
};
