name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build
        run: npm run build
        env:
          CI: false
          REACT_APP_USER_ID: '${{ secrets.REACT_APP_USER_ID }}'
          REACT_APP_SUPABASE_KEY: '${{ secrets.REACT_APP_SUPABASE_KEY }}'
      
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ELSHAFEY_PORTFOLIO }}'
          channelId: live
          projectId: elshafey-portfolio
